(cl:defpackage humanoid_nav_msgs-msg
  (:use )
  (:export
   "<EXECFOOTSTEPSACTION>"
   "EXECFOOTSTEPSACTION"
   "<EXECFOOTSTEPSACTIONFEEDBACK>"
   "EXECFOOTSTEPSACTIONFEEDBACK"
   "<EXECFOOTSTEPSACTIONGOAL>"
   "EXECFOOTSTEPSACTIONGOAL"
   "<EXECFOOTSTEPSACTIONRESULT>"
   "EXECFOOTSTEPSACTIONRESULT"
   "<EXECFOOTSTEPSFEEDBACK>"
   "EXECFOOTSTEPSFEEDBACK"
   "<EXECFOOTSTEPSGOAL>"
   "EXECFOOTSTEPSGOAL"
   "<EXECFOOTSTEPSRESULT>"
   "EXECFOOTSTEPSRESULT"
   "<STEPTARGET>"
   "STEPTARGET"
  ))

