; Auto-generated. Do not edit!


(cl:in-package humanoid_nav_msgs-msg)


;//! \htmlinclude ExecFootstepsResult.msg.html

(cl:defclass <ExecFootstepsResult> (roslisp-msg-protocol:ros-message)
  ((executed_footsteps
    :reader executed_footsteps
    :initarg :executed_footsteps
    :type (cl:vector humanoid_nav_msgs-msg:StepTarget)
   :initform (cl:make-array 0 :element-type 'humanoid_nav_msgs-msg:StepTarget :initial-element (cl:make-instance 'humanoid_nav_msgs-msg:StepTarget))))
)

(cl:defclass ExecFootstepsResult (<ExecFootstepsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecFootstepsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecFootstepsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name humanoid_nav_msgs-msg:<ExecFootstepsResult> is deprecated: use humanoid_nav_msgs-msg:ExecFootstepsResult instead.")))

(cl:ensure-generic-function 'executed_footsteps-val :lambda-list '(m))
(cl:defmethod executed_footsteps-val ((m <ExecFootstepsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader humanoid_nav_msgs-msg:executed_footsteps-val is deprecated.  Use humanoid_nav_msgs-msg:executed_footsteps instead.")
  (executed_footsteps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecFootstepsResult>) ostream)
  "Serializes a message object of type '<ExecFootstepsResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'executed_footsteps))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'executed_footsteps))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecFootstepsResult>) istream)
  "Deserializes a message object of type '<ExecFootstepsResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'executed_footsteps) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'executed_footsteps)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'humanoid_nav_msgs-msg:StepTarget))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecFootstepsResult>)))
  "Returns string type for a message object of type '<ExecFootstepsResult>"
  "humanoid_nav_msgs/ExecFootstepsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecFootstepsResult)))
  "Returns string type for a message object of type 'ExecFootstepsResult"
  "humanoid_nav_msgs/ExecFootstepsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecFootstepsResult>)))
  "Returns md5sum for a message object of type '<ExecFootstepsResult>"
  "5dfde2cb244d6c76567d3c52c40a988c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecFootstepsResult)))
  "Returns md5sum for a message object of type 'ExecFootstepsResult"
  "5dfde2cb244d6c76567d3c52c40a988c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecFootstepsResult>)))
  "Returns full string definition for message of type '<ExecFootstepsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%humanoid_nav_msgs/StepTarget[] executed_footsteps~%~%================================================================================~%MSG: humanoid_nav_msgs/StepTarget~%# Target for a single stepping motion of a humanoid's leg~%~%geometry_msgs/Pose2D pose   # step pose as relative offset to last leg~%uint8 leg                   # which leg to use (left/right, see below)~%~%uint8 right=0               # right leg constant~%uint8 left=1                # left leg constant~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecFootstepsResult)))
  "Returns full string definition for message of type 'ExecFootstepsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%humanoid_nav_msgs/StepTarget[] executed_footsteps~%~%================================================================================~%MSG: humanoid_nav_msgs/StepTarget~%# Target for a single stepping motion of a humanoid's leg~%~%geometry_msgs/Pose2D pose   # step pose as relative offset to last leg~%uint8 leg                   # which leg to use (left/right, see below)~%~%uint8 right=0               # right leg constant~%uint8 left=1                # left leg constant~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecFootstepsResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'executed_footsteps) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecFootstepsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecFootstepsResult
    (cl:cons ':executed_footsteps (executed_footsteps msg))
))
