// Generated by gencpp from file tiago_pcl_tutorial/PlaneCoefficients.msg
// DO NOT EDIT!


#ifndef TIAGO_PCL_TUTORIAL_MESSAGE_PLANECOEFFICIENTS_H
#define TIAGO_PCL_TUTORIAL_MESSAGE_PLANECOEFFICIENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tiago_pcl_tutorial
{
template <class ContainerAllocator>
struct PlaneCoefficients_
{
  typedef PlaneCoefficients_<ContainerAllocator> Type;

  PlaneCoefficients_()
    : header()
    , A(0.0)
    , B(0.0)
    , C(0.0)
    , D(0.0)  {
    }
  PlaneCoefficients_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , A(0.0)
    , B(0.0)
    , C(0.0)
    , D(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _A_type;
  _A_type A;

   typedef double _B_type;
  _B_type B;

   typedef double _C_type;
  _C_type C;

   typedef double _D_type;
  _D_type D;





  typedef boost::shared_ptr< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> const> ConstPtr;

}; // struct PlaneCoefficients_

typedef ::tiago_pcl_tutorial::PlaneCoefficients_<std::allocator<void> > PlaneCoefficients;

typedef boost::shared_ptr< ::tiago_pcl_tutorial::PlaneCoefficients > PlaneCoefficientsPtr;
typedef boost::shared_ptr< ::tiago_pcl_tutorial::PlaneCoefficients const> PlaneCoefficientsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator1> & lhs, const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.A == rhs.A &&
    lhs.B == rhs.B &&
    lhs.C == rhs.C &&
    lhs.D == rhs.D;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator1> & lhs, const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago_pcl_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d4c9b5fdb3af7a139e7d73556e46d69";
  }

  static const char* value(const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d4c9b5fdb3af7a1ULL;
  static const uint64_t static_value2 = 0x39e7d73556e46d69ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago_pcl_tutorial/PlaneCoefficients";
  }

  static const char* value(const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# 3D plane coefficients of the explicit equation AX + BY + CZ + D = 0\n"
"float64 A\n"
"float64 B\n"
"float64 C\n"
"float64 D\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.C);
      stream.next(m.D);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaneCoefficients_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago_pcl_tutorial::PlaneCoefficients_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "A: ";
    Printer<double>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<double>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<double>::stream(s, indent + "  ", v.C);
    s << indent << "D: ";
    Printer<double>::stream(s, indent + "  ", v.D);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO_PCL_TUTORIAL_MESSAGE_PLANECOEFFICIENTS_H
