(cl:defpackage pal_walking_msgs-srv
  (:use )
  (:export
   "MOVEHIPFEET"
   "<MOVEHIPFEET-REQUEST>"
   "MOVEHIPFEET-REQUEST"
   "<MOVEHIPFEET-RESPONSE>"
   "MOVEHIPFEET-RESPONSE"
   "SIT"
   "<SIT-REQUEST>"
   "SIT-REQUEST"
   "<SIT-RESPONSE>"
   "SIT-RESPONSE"
   "STEPOVER"
   "<STEPOVER-REQUEST>"
   "STEPOVER-REQUEST"
   "<STEPOVER-RESPONSE>"
   "STEPOVER-RESPONSE"
   "WALKSTEPS"
   "<WALKSTEPS-REQUEST>"
   "WALKSTEPS-REQUEST"
   "<WALKSTEPS-RESPONSE>"
   "WALKSTEPS-RESPONSE"
  ))

