(cl:defpackage pal_web_msgs-msg
  (:use )
  (:export
   "<GETUSERINPUTACTION>"
   "GETUSERINPUTACTION"
   "<GETUSERINPUTACTIONFEEDBACK>"
   "GETUSERINPUTACTIONFEEDBACK"
   "<GETUSERINPUTACTIONGOAL>"
   "GETUSERINPUTACTIONGOAL"
   "<GETUSERINPUTACTIONRESULT>"
   "GETUSERINPUTACTIONRESULT"
   "<GETUSERINPUTFEEDBACK>"
   "GETUSERINPUTFEEDBACK"
   "<GETUSERINPUTGOAL>"
   "GETUSERINPUTGOAL"
   "<GETUSERINPUTRESULT>"
   "GETUSERINPUTRESULT"
   "<WEBGOTO>"
   "WEBGOTO"
  ))

