; Auto-generated. Do not edit!


(cl:in-package pal_web_msgs-msg)


;//! \htmlinclude GetUserInputFeedback.msg.html

(cl:defclass <GetUserInputFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetUserInputFeedback (<GetUserInputFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetUserInputFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetUserInputFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_web_msgs-msg:<GetUserInputFeedback> is deprecated: use pal_web_msgs-msg:GetUserInputFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetUserInputFeedback>) ostream)
  "Serializes a message object of type '<GetUserInputFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetUserInputFeedback>) istream)
  "Deserializes a message object of type '<GetUserInputFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetUserInputFeedback>)))
  "Returns string type for a message object of type '<GetUserInputFeedback>"
  "pal_web_msgs/GetUserInputFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetUserInputFeedback)))
  "Returns string type for a message object of type 'GetUserInputFeedback"
  "pal_web_msgs/GetUserInputFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetUserInputFeedback>)))
  "Returns md5sum for a message object of type '<GetUserInputFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetUserInputFeedback)))
  "Returns md5sum for a message object of type 'GetUserInputFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetUserInputFeedback>)))
  "Returns full string definition for message of type '<GetUserInputFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetUserInputFeedback)))
  "Returns full string definition for message of type 'GetUserInputFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetUserInputFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetUserInputFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GetUserInputFeedback
))
