; Auto-generated. Do not edit!


(cl:in-package pal_web_msgs-msg)


;//! \htmlinclude GetUserInputResult.msg.html

(cl:defclass <GetUserInputResult> (roslisp-msg-protocol:ros-message)
  ((input
    :reader input
    :initarg :input
    :type pal_interaction_msgs-msg:Input
    :initform (cl:make-instance 'pal_interaction_msgs-msg:Input)))
)

(cl:defclass GetUserInputResult (<GetUserInputResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetUserInputResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetUserInputResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pal_web_msgs-msg:<GetUserInputResult> is deprecated: use pal_web_msgs-msg:GetUserInputResult instead.")))

(cl:ensure-generic-function 'input-val :lambda-list '(m))
(cl:defmethod input-val ((m <GetUserInputResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pal_web_msgs-msg:input-val is deprecated.  Use pal_web_msgs-msg:input instead.")
  (input m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetUserInputResult>) ostream)
  "Serializes a message object of type '<GetUserInputResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'input) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetUserInputResult>) istream)
  "Deserializes a message object of type '<GetUserInputResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'input) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetUserInputResult>)))
  "Returns string type for a message object of type '<GetUserInputResult>"
  "pal_web_msgs/GetUserInputResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetUserInputResult)))
  "Returns string type for a message object of type 'GetUserInputResult"
  "pal_web_msgs/GetUserInputResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetUserInputResult>)))
  "Returns md5sum for a message object of type '<GetUserInputResult>"
  "e51b609d0dcba5a1ff33c6656b8ac4e3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetUserInputResult)))
  "Returns md5sum for a message object of type 'GetUserInputResult"
  "e51b609d0dcba5a1ff33c6656b8ac4e3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetUserInputResult>)))
  "Returns full string definition for message of type '<GetUserInputResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%pal_interaction_msgs/Input input~%~%================================================================================~%MSG: pal_interaction_msgs/Input~%#action to perform~%string INPUT_ACCEPT = INPUT_ACCEPT~%string INPUT_REJECT = INPUT_REJECT~%string INPUT_CANCEL = INPUT_CANCEL~%~%# Deprecated in favor of the INPUT_* above. Will be removed in a future message~%string OK = ok~%string YES = yes~%string NO = no~%string CANCEL = cancel~%string ABORT = abort~%~%# Can be any of the above, and additionally any custom action you want~%string action~%~%InputArgument[] args~%~%================================================================================~%MSG: pal_interaction_msgs/InputArgument~%string key~%string value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetUserInputResult)))
  "Returns full string definition for message of type 'GetUserInputResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%pal_interaction_msgs/Input input~%~%================================================================================~%MSG: pal_interaction_msgs/Input~%#action to perform~%string INPUT_ACCEPT = INPUT_ACCEPT~%string INPUT_REJECT = INPUT_REJECT~%string INPUT_CANCEL = INPUT_CANCEL~%~%# Deprecated in favor of the INPUT_* above. Will be removed in a future message~%string OK = ok~%string YES = yes~%string NO = no~%string CANCEL = cancel~%string ABORT = abort~%~%# Can be any of the above, and additionally any custom action you want~%string action~%~%InputArgument[] args~%~%================================================================================~%MSG: pal_interaction_msgs/InputArgument~%string key~%string value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetUserInputResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'input))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetUserInputResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GetUserInputResult
    (cl:cons ':input (input msg))
))
