(cl:defpackage humanoid_nav_msgs-srv
  (:use )
  (:export
   "CLIPFOOTSTEP"
   "<CLIPFOOTSTEP-REQUEST>"
   "CLIPFOOTSTEP-REQUEST"
   "<CLIPFOOTSTEP-RESPONSE>"
   "CLIPFOOTSTEP-RESPONSE"
   "PLANFOOTSTEPS"
   "<PLANFOOTSTEPS-REQUEST>"
   "PLANFOOTSTEPS-REQUEST"
   "<PLANFOOTSTEPS-RESPONSE>"
   "PLANFOOTSTEPS-RESPONSE"
   "PLANFOOTSTEPSBETWEENFEET"
   "<PLANFOOTSTEPSBETWEENFEET-REQUEST>"
   "PLANFOOTSTEPSBETWEENFEET-REQUEST"
   "<PLANFOOTSTEPSBETWEENFEET-RESPONSE>"
   "PLANFOOTSTEPSBETWEENFEET-RESPONSE"
   "STEPTARGETSERVICE"
   "<STEPTARGETSERVICE-REQUEST>"
   "STEPTARGETSERVICE-REQUEST"
   "<STEPTARGETSERVICE-RESPONSE>"
   "STEPTARGETSERVICE-RESPONSE"
  ))

