// Auto-generated. Do not edit!

// (in-package tf_lookup.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TfStreamResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.subscription_id = null;
      this.topic = null;
    }
    else {
      if (initObj.hasOwnProperty('subscription_id')) {
        this.subscription_id = initObj.subscription_id
      }
      else {
        this.subscription_id = '';
      }
      if (initObj.hasOwnProperty('topic')) {
        this.topic = initObj.topic
      }
      else {
        this.topic = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TfStreamResult
    // Serialize message field [subscription_id]
    bufferOffset = _serializer.string(obj.subscription_id, buffer, bufferOffset);
    // Serialize message field [topic]
    bufferOffset = _serializer.string(obj.topic, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TfStreamResult
    let len;
    let data = new TfStreamResult(null);
    // Deserialize message field [subscription_id]
    data.subscription_id = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [topic]
    data.topic = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.subscription_id.length;
    length += object.topic.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'tf_lookup/TfStreamResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a8f3e325856c12da00435a78bf464739';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    string subscription_id
    string topic
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TfStreamResult(null);
    if (msg.subscription_id !== undefined) {
      resolved.subscription_id = msg.subscription_id;
    }
    else {
      resolved.subscription_id = ''
    }

    if (msg.topic !== undefined) {
      resolved.topic = msg.topic;
    }
    else {
      resolved.topic = ''
    }

    return resolved;
    }
};

module.exports = TfStreamResult;
