// Generated by gencpp from file pal_walking_msgs/StepOver.msg
// DO NOT EDIT!


#ifndef PAL_WALKING_MSGS_MESSAGE_STEPOVER_H
#define PAL_WALKING_MSGS_MESSAGE_STEPOVER_H

#include <ros/service_traits.h>


#include <pal_walking_msgs/StepOverRequest.h>
#include <pal_walking_msgs/StepOverResponse.h>


namespace pal_walking_msgs
{

struct StepOver
{

typedef StepOverRequest Request;
typedef StepOverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StepOver
} // namespace pal_walking_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_walking_msgs::StepOver > {
  static const char* value()
  {
    return "b3759907c1da99fedab7db53a18a936b";
  }

  static const char* value(const ::pal_walking_msgs::StepOver&) { return value(); }
};

template<>
struct DataType< ::pal_walking_msgs::StepOver > {
  static const char* value()
  {
    return "pal_walking_msgs/StepOver";
  }

  static const char* value(const ::pal_walking_msgs::StepOver&) { return value(); }
};


// service_traits::MD5Sum< ::pal_walking_msgs::StepOverRequest> should match
// service_traits::MD5Sum< ::pal_walking_msgs::StepOver >
template<>
struct MD5Sum< ::pal_walking_msgs::StepOverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_walking_msgs::StepOver >::value();
  }
  static const char* value(const ::pal_walking_msgs::StepOverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_walking_msgs::StepOverRequest> should match
// service_traits::DataType< ::pal_walking_msgs::StepOver >
template<>
struct DataType< ::pal_walking_msgs::StepOverRequest>
{
  static const char* value()
  {
    return DataType< ::pal_walking_msgs::StepOver >::value();
  }
  static const char* value(const ::pal_walking_msgs::StepOverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_walking_msgs::StepOverResponse> should match
// service_traits::MD5Sum< ::pal_walking_msgs::StepOver >
template<>
struct MD5Sum< ::pal_walking_msgs::StepOverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_walking_msgs::StepOver >::value();
  }
  static const char* value(const ::pal_walking_msgs::StepOverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_walking_msgs::StepOverResponse> should match
// service_traits::DataType< ::pal_walking_msgs::StepOver >
template<>
struct DataType< ::pal_walking_msgs::StepOverResponse>
{
  static const char* value()
  {
    return DataType< ::pal_walking_msgs::StepOver >::value();
  }
  static const char* value(const ::pal_walking_msgs::StepOverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_WALKING_MSGS_MESSAGE_STEPOVER_H
