; Auto-generated. Do not edit!


(cl:in-package play_motion_msgs-msg)


;//! \htmlinclude PlayMotionFeedback.msg.html

(cl:defclass <PlayMotionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlayMotionFeedback (<PlayMotionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayMotionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayMotionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name play_motion_msgs-msg:<PlayMotionFeedback> is deprecated: use play_motion_msgs-msg:PlayMotionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayMotionFeedback>) ostream)
  "Serializes a message object of type '<PlayMotionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayMotionFeedback>) istream)
  "Deserializes a message object of type '<PlayMotionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayMotionFeedback>)))
  "Returns string type for a message object of type '<PlayMotionFeedback>"
  "play_motion_msgs/PlayMotionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayMotionFeedback)))
  "Returns string type for a message object of type 'PlayMotionFeedback"
  "play_motion_msgs/PlayMotionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayMotionFeedback>)))
  "Returns md5sum for a message object of type '<PlayMotionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayMotionFeedback)))
  "Returns md5sum for a message object of type 'PlayMotionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayMotionFeedback>)))
  "Returns full string definition for message of type '<PlayMotionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayMotionFeedback)))
  "Returns full string definition for message of type 'PlayMotionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayMotionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayMotionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayMotionFeedback
))
