(cl:defpackage play_motion_msgs-srv
  (:use )
  (:export
   "ISALREADYTHERE"
   "<ISALREADYTHERE-REQUEST>"
   "ISALREADYTHERE-REQUEST"
   "<ISALREADYTHERE-RESPONSE>"
   "ISALREADYTHERE-RESPONSE"
   "LISTMOTIONS"
   "<LISTMOTIONS-REQUEST>"
   "LISTMOTIONS-REQUEST"
   "<LISTMOTIONS-RESPONSE>"
   "LISTMOTIONS-RESPONSE"
  ))

