// Generated by gencpp from file pal_web_msgs/GetUserInputActionGoal.msg
// DO NOT EDIT!


#ifndef PAL_WEB_MSGS_MESSAGE_GETUSERINPUTACTIONGOAL_H
#define PAL_WEB_MSGS_MESSAGE_GETUSERINPUTACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <pal_web_msgs/GetUserInputGoal.h>

namespace pal_web_msgs
{
template <class ContainerAllocator>
struct GetUserInputActionGoal_
{
  typedef GetUserInputActionGoal_<ContainerAllocator> Type;

  GetUserInputActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  GetUserInputActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::pal_web_msgs::GetUserInputGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GetUserInputActionGoal_

typedef ::pal_web_msgs::GetUserInputActionGoal_<std::allocator<void> > GetUserInputActionGoal;

typedef boost::shared_ptr< ::pal_web_msgs::GetUserInputActionGoal > GetUserInputActionGoalPtr;
typedef boost::shared_ptr< ::pal_web_msgs::GetUserInputActionGoal const> GetUserInputActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator1> & lhs, const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator1> & lhs, const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pal_web_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6187ed7f15bf16fb2deefdc64aa97360";
  }

  static const char* value(const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6187ed7f15bf16fbULL;
  static const uint64_t static_value2 = 0x2deefdc64aa97360ULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pal_web_msgs/GetUserInputActionGoal";
  }

  static const char* value(const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"GetUserInputGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pal_web_msgs/GetUserInputGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"pal_web_msgs/WebGoTo web_go_to # Web to display for requesting feedback\n"
"pal_interaction_msgs/TtsGoal question_tts # TTS question, asked before waiting for feedback\n"
"string[] valid_asr_inputs # empty is no ASR, can be regex\n"
"string asr_language # empty is current default\n"
"duration asr_timeout\n"
"bool retry_asr\n"
"pal_interaction_msgs/TtsGoal retry_tts # If retrying, say this setence\n"
"bool wait_for_interaction # If true, wait for an interaction before starting the ASR\n"
"\n"
"================================================================================\n"
"MSG: pal_web_msgs/WebGoTo\n"
"uint8 IMAGE = 0\n"
"uint8 VIDEO = 1\n"
"uint8 URI   = 2\n"
"uint8 URL = 3\n"
"uint8 TOUCH_PAGE = 4\n"
"uint8 type # one of the enum above\n"
"\n"
"string value # Destination (an image, a video or a uri)\n"
"\n"
"================================================================================\n"
"MSG: pal_interaction_msgs/TtsGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"## goal definition\n"
"\n"
"# utterance will contain indications to construct\n"
"# the text to be spoken.\n"
"# It must be specified in a section/key format \n"
"# for internationalisation. The actual text will\n"
"# be obtained from configuration files as in pal_tts_cfg pkg.\n"
" \n"
"I18nText text\n"
"TtsText rawtext\n"
"\n"
"# This is to suggest a voice name to the \n"
"# tts engine. For the same language we might have\n"
"# a variety of voices available, and this variable \n"
"# is to choose one among them. \n"
"# (not implemented yet)\n"
"string speakerName\n"
"\n"
"# Time to wait before synthesising the text itself.\n"
"# It can be used to produced delayed speech.\n"
"float64 wait_before_speaking\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pal_interaction_msgs/I18nText\n"
"# section/key is used as in examples in the pal_tts_cfg pkg.\n"
"string section\n"
"string key\n"
"\n"
"# language id, must be speficied using RFC 3066\n"
"string lang_id\n"
"\n"
"# arguments contain the values by which \n"
"# occurrences of '%s' will be replaced in the \n"
"# main text.\n"
"# This only supports up to 2 arguments and no recursion.\n"
"# However, recursion and more argumnents are\n"
"# planned to be supported in the future.\n"
"I18nArgument[] arguments\n"
"\n"
"================================================================================\n"
"MSG: pal_interaction_msgs/I18nArgument\n"
"# section key, override the value in expanded.\n"
"# Use expanded for text that do not need expansion.\n"
"# Please note that expanded here will not be translated \n"
"# to any language.\n"
"\n"
"string section\n"
"string key\n"
"string expanded\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pal_interaction_msgs/TtsText\n"
"# this message is to specify \n"
"# raw text to the TTS server. \n"
"\n"
"string text\n"
"\n"
"# Language id in RFC 3066 format\n"
"# This field is mandatory\n"
"string lang_id\n"
;
  }

  static const char* value(const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetUserInputActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pal_web_msgs::GetUserInputActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::pal_web_msgs::GetUserInputGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAL_WEB_MSGS_MESSAGE_GETUSERINPUTACTIONGOAL_H
