; Auto-generated. Do not edit!


(cl:in-package tiago_pick_demo-msg)


;//! \htmlinclude PickUpPoseGoal.msg.html

(cl:defclass <PickUpPoseGoal> (roslisp-msg-protocol:ros-message)
  ((object_pose
    :reader object_pose
    :initarg :object_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass PickUpPoseGoal (<PickUpPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickUpPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickUpPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago_pick_demo-msg:<PickUpPoseGoal> is deprecated: use tiago_pick_demo-msg:PickUpPoseGoal instead.")))

(cl:ensure-generic-function 'object_pose-val :lambda-list '(m))
(cl:defmethod object_pose-val ((m <PickUpPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago_pick_demo-msg:object_pose-val is deprecated.  Use tiago_pick_demo-msg:object_pose instead.")
  (object_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickUpPoseGoal>) ostream)
  "Serializes a message object of type '<PickUpPoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickUpPoseGoal>) istream)
  "Deserializes a message object of type '<PickUpPoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickUpPoseGoal>)))
  "Returns string type for a message object of type '<PickUpPoseGoal>"
  "tiago_pick_demo/PickUpPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickUpPoseGoal)))
  "Returns string type for a message object of type 'PickUpPoseGoal"
  "tiago_pick_demo/PickUpPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickUpPoseGoal>)))
  "Returns md5sum for a message object of type '<PickUpPoseGoal>"
  "ce62f562fe862ddbebe5377023767cb7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickUpPoseGoal)))
  "Returns md5sum for a message object of type 'PickUpPoseGoal"
  "ce62f562fe862ddbebe5377023767cb7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickUpPoseGoal>)))
  "Returns full string definition for message of type '<PickUpPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped object_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickUpPoseGoal)))
  "Returns full string definition for message of type 'PickUpPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped object_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickUpPoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickUpPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PickUpPoseGoal
    (cl:cons ':object_pose (object_pose msg))
))
