; Auto-generated. Do not edit!


(cl:in-package tf_lookup-msg)


;//! \htmlinclude TfStreamFeedback.msg.html

(cl:defclass <TfStreamFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TfStreamFeedback (<TfStreamFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TfStreamFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TfStreamFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tf_lookup-msg:<TfStreamFeedback> is deprecated: use tf_lookup-msg:TfStreamFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TfStreamFeedback>) ostream)
  "Serializes a message object of type '<TfStreamFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TfStreamFeedback>) istream)
  "Deserializes a message object of type '<TfStreamFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TfStreamFeedback>)))
  "Returns string type for a message object of type '<TfStreamFeedback>"
  "tf_lookup/TfStreamFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TfStreamFeedback)))
  "Returns string type for a message object of type 'TfStreamFeedback"
  "tf_lookup/TfStreamFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TfStreamFeedback>)))
  "Returns md5sum for a message object of type '<TfStreamFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TfStreamFeedback)))
  "Returns md5sum for a message object of type 'TfStreamFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TfStreamFeedback>)))
  "Returns full string definition for message of type '<TfStreamFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TfStreamFeedback)))
  "Returns full string definition for message of type 'TfStreamFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TfStreamFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TfStreamFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TfStreamFeedback
))
