// Auto-generated. Do not edit!

// (in-package play_motion_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let PlayMotionActionGoal = require('./PlayMotionActionGoal.js');
let PlayMotionActionResult = require('./PlayMotionActionResult.js');
let PlayMotionActionFeedback = require('./PlayMotionActionFeedback.js');

//-----------------------------------------------------------

class PlayMotionAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new PlayMotionActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new PlayMotionActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new PlayMotionActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PlayMotionAction
    // Serialize message field [action_goal]
    bufferOffset = PlayMotionActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = PlayMotionActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = PlayMotionActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PlayMotionAction
    let len;
    let data = new PlayMotionAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = PlayMotionActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = PlayMotionActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = PlayMotionActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += PlayMotionActionGoal.getMessageSize(object.action_goal);
    length += PlayMotionActionResult.getMessageSize(object.action_result);
    length += PlayMotionActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'play_motion_msgs/PlayMotionAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b18530db1ae596c4c0ca2ede0819fc9e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    PlayMotionActionGoal action_goal
    PlayMotionActionResult action_result
    PlayMotionActionFeedback action_feedback
    
    ================================================================================
    MSG: play_motion_msgs/PlayMotionActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    PlayMotionGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: play_motion_msgs/PlayMotionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string motion_name
    bool skip_planning
    int32 priority
    
    ================================================================================
    MSG: play_motion_msgs/PlayMotionActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    PlayMotionResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: play_motion_msgs/PlayMotionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 error_code
    int32 SUCCEEDED             = 1
    int32 MOTION_NOT_FOUND      = -1
    # controller error codes
    int32 CONTROLLER_BUSY       = -3
    int32 MISSING_CONTROLLER    = -4
    int32 TRAJECTORY_ERROR      = -5
    int32 GOAL_NOT_REACHED      = -6
    # planner error codes
    int32 PLANNER_OFFLINE       = -7
    int32 NO_PLAN_FOUND         = -8
    #other
    int32 OTHER_ERROR           = -42
    
    string error_string
    
    ================================================================================
    MSG: play_motion_msgs/PlayMotionActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    PlayMotionFeedback feedback
    
    ================================================================================
    MSG: play_motion_msgs/PlayMotionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PlayMotionAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = PlayMotionActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new PlayMotionActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = PlayMotionActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new PlayMotionActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = PlayMotionActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new PlayMotionActionFeedback()
    }

    return resolved;
    }
};

module.exports = PlayMotionAction;
