(cl:defpackage dynamic_introspection-msg
  (:use )
  (:export
   "<BOOLPARAMETER>"
   "BOOLPARAMETER"
   "<DOUBLEPARAMETER>"
   "DOUBLEPARAMETER"
   "<INTPARAMETER>"
   "INTPARAMETER"
   "<INTROSPECTIONMSG>"
   "INTROSPECTIONMSG"
   "<MARKERPARAMETER>"
   "MARKERPARAMETER"
  ))

